resolver: nightly-2024-06-13
packages:
- .
ghc-options:
  "$locals":
    -Wall -Wcompat
    -Widentities
    -Wincomplete-record-updates
    -Wincomplete-uni-patterns
    -Wmissing-deriving-strategies
    -Wmissing-export-lists
    -Wmissing-exported-signatures
    -Wmissing-home-modules
    -Wpartial-fields
    -Wprepositive-qualified-module
    -Wredundant-constraints
    -Wunused-binds
    -Wunused-packages
    -Wunused-type-patterns
    -Wno-unticked-promoted-constructors
extra-deps:
  - env-guard-0.2@sha256:99b89cde1ed6d599880dfbc72b2c9a75ced57b7800a70dcb57d3e3e89e42184c,1312
  - text-display-0.0.5.2@sha256:6e6a5bf1c83dfa6c34692ed5d8ea87f1bd385984309b42c302f2156f4d82477b,2670
  - git: https://github.com/tbidne/algebra-simple.git
    commit: f8590486ec0fc66acf7db20308e1ed6993a52151
  - git: https://github.com/tbidne/bounds.git
    commit: f93b202c9d154b25b42b048570cf6648451aa577
  - git: https://github.com/tbidne/monad-effects.git
    commit: aeecb47f4aa144e686a7d596670bade5bf47e7d4
    subdirs:
      - lib/effects-env
      - lib/effects-exceptions
      - lib/effects-fs
      - lib/effects-ioref
      - lib/effects-optparse
      - lib/effects-terminal
      - lib/effects-time
      - lib/effects-unix-compat
  - git: https://github.com/tbidne/refined-extras.git
    commit: 9c0e3b2f7e888427338e581449904d700d40c0de
