###############################################################################
#                                   DISPLAY                                   #
###############################################################################

# If enabled, the terminal output uses colors. Defaults to true.
color = false

# If enabled, the terminal output uses unicode emojis. Defaults to true.
unicode = false

###############################################################################
#                                  Index Path                                 #
###############################################################################

# Selects a name from index-legend to read by default. Can be overwritten by
# the CLI.
index-name = 'default'

# Map from names to paths. Allows one to specific a name rather than a full
# path. Paths can be absolute or relative to this toml file.
index-legend = [
  { name = 'default', path = 'index.json' },
  { name = 'another', path = 'index2.json' }
]
